"""init

Revision ID: 6acfa7264048
Revises: 
Create Date: 2025-10-01 10:31:27.482952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6acfa7264048'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('medical_specialty', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('medical_license_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phoneno', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_doctor_email'), 'doctor', ['email'], unique=True)
    op.create_index(op.f('ix_doctor_medical_license_number'), 'doctor', ['medical_license_number'], unique=True)
    op.create_index(op.f('ix_doctor_uid'), 'doctor', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_uid'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_medical_license_number'), table_name='doctor')
    op.drop_index(op.f('ix_doctor_email'), table_name='doctor')
    op.drop_table('doctor')
    # ### end Alembic commands ###
